kanta = input("Kirjoita tähän suorakulmion kanta ")
kanta = int(kanta)
korkeus = input("ja korkeus ")
korkeus = int(korkeus)
print("Suorakulmion piiri on ", (kanta + kanta + korkeus + korkeus))
print("suorakulmion pinta-ala on ", (kanta * korkeus))